const List<Map<String, dynamic>> fakeData = [
  {
    'id': 1,
    'typeOfService': 'Mock Test',
    'title': 'Physics Mock Test',
    'seatsAvailable': 5,
    'fullAddress': '123 Main St, City, Country',
    'totalMarks': 100,
    'dateAndTime': '2024-08-01 10:00 AM',
    'duration': '2 hours',
    'price': 500,
  },
  {
    'id': 2,
    'typeOfService': 'Doubt Session',
    'title': 'Math Doubt Session',
    'seatsAvailable': 3,
    'fullAddress': '456 Second St, City, Country',
    'dateAndTime': '2024-08-02 11:00 AM',
    'price': 300,
  },
  {
    'id': 3,
    'typeOfService': '1:1 Session',
    'title': 'Chemistry 1:1 Session',
    'seatsAvailable': 1,
    'fullAddress': '789 Third St, City, Country',
    'dateAndTime': '2024-08-03 12:00 PM',
    'price': 700,
  },
  {
    'id': 4,
    'typeOfService': 'Mock Test',
    'title': 'Biology Mock Test',
    'seatsAvailable': 10,
    'fullAddress': '101 First St, City, Country',
    'totalMarks': 150,
    'dateAndTime': '2024-08-04 09:00 AM',
    'duration': '3 hours',
    'price': 400,
  },
  {
    'id': 5,
    'typeOfService': 'Doubt Session',
    'title': 'English Doubt Session',
    'seatsAvailable': 4,
    'fullAddress': '202 Fourth St, City, Country',
    'dateAndTime': '2024-08-05 02:00 PM',
    'price': 250,
  },
  {
    'id': 6,
    'typeOfService': '1:1 Session',
    'title': 'History 1:1 Session',
    'seatsAvailable': 1,
    'fullAddress': '303 Fifth St, City, Country',
    'dateAndTime': '2024-08-06 03:00 PM',
    'price': 600,
  },
];
